services:
  - type: web
    name: ddakpool-api
    runtime: node
    buildCommand: npm install
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: CORS_ALLOW_VERCEL
        value: "true"
      - key: CORS_ORIGIN
        value: "http://localhost:3000,https://pm6-final-group-10-fe.vercel.app"
